version: '3'
services:
  oracle:
    image: oracle/database:23.2.0-free
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./oradata:/opt/oracle/oradata:rw
      - ./admin:/opt/oracle/admin:rw
