version: '3'
services:
  oracle:
    image: oracle/database:23.2.0-free
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=batatinha
      - ORACLE_CHARACTERSET=WE8ISO8859P1
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./admin:/opt/oracle/admin
      - ./sqlnet.ora:/opt/oracle/oradata/dbconfig/FREE/sqlnet.ora
