version: '3'
services:
  oracle:
    #image: oracle/database:23.2.0-free
    image: container-registry.oracle.com/database/free #https://www.oracle.com/database/free/get-started
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=batatinha
      - ORACLE_CHARACTERSET=WE8ISO8859P1
    volumes:
      - oracle-data:/opt/oracle/oradata
      #- oracle-dpdump:/opt/oracle/admin/FREE/dpdump
      #- ./sqlnet.ora:/opt/oracle/oradata/dbconfig/FREE/sqlnet.ora:ro

volumes:
  oracle-data:
    external: true
