version: '3'
services:
  kali:
    build: .
    image: frakley/kali-rolling
    container_name: kali
    hostname: kali
    #volumes:
    #  - ./home:/home
    restart: unless-stopped
    #restart: always
    entrypoint: ["/entrypoint.sh"]
    ports:
      - 3389:3390
      - 2222:22
